---
# Apply latest Ruby style guide and newly introduced cops
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Include:
    - Gemfile
    - Rakefile
    - '**/*.rb'
  Exclude:
    - _snippets/*

# ignore block length where unavoidable (e.g., framework requires it)
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - app/application/controllers/*.rb # Roda's nested controllers require large blocks
    - spec/**/* # Minitest's nested test structure requires large blocks
    - Rakefile # Rake namespaces produce large blocks

Metrics/ParameterLists:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: true
  Exclude:
    - app/domain/popularity/values/popularity_levels.rb

Metrics/PerceivedComplexity:
  Enabled: true
  Exclude:
    - app/domain/popularity/values/popularity_levels.rb

# allow unsafe YAML loading in test code only
Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

Style/HashSyntax:
  Enabled: true
  Exclude:
    - Rakefile

Style/SymbolArray:
  Enabled: true
  Exclude:
    - Rakefile
    - app/infrastructure/database/migrations/*.rb

Style/SingleLineMethods:
  Enabled: false

Style/SymbolLiteral:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: true
  Exclude:
    - Rakefile
    - config/environment.rb

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false