# frozen_string_literal: true

module MerciDanke
  module Request
    # Application value for the path of a requested pokemon
    class LikePath
      def initialize(target_id, request)
        # for pokemon is id (generated by PokeZon)
        # for product is origin_id (generated by Amazon)
        @target_id = target_id
        @request = request
      end

      attr_reader :target_id
    end
  end
end
