---
development:
  API_HOST: http://localhost:9000
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/dev.db

test:
  API_HOST: http://localhost:9090
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/test.db

app_test:
  API_HOST: http://localhost:9090
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/test.db
production:
  API_HOST: https://mercidanke2020-api.herokuapp.com
  # Infrastructure