---
development:
  API_HOST: http://localhost:9292
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/dev.db
  POKEMON_NUM: 800

test:
  API_HOST: http://localhost:9292
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/test.db
  POKEMON_NUM: 5

app_test:
  API_HOST: http://localhost:9292
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/test.db
production:
  API_HOST: https://pokezon-api.herokuapp.com
  POKEMON_NUM: 800