name: API continuous integeration

on:
  push:
    branches: [ master ]

  pull_request:
    branches: 
      - '**'

  workflow_dispatch:


jobs:
  api_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v2
  
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup test database
        run: RACK_ENV=test bundle exec rake db:migrate

      - name: Run all specs
        env:
          API_KEY: ${{ secrets.API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SEARCH_QUEUE: ${{ secrets.SEARCH_QUEUE }}
          SEARCH_QUEUE_URL: ${{ secrets.SEARCH_QUEUE_URL }}
        run: |
          rake worker:run:test &
          bundle exec rake spec
